module.exports={
    ghPayInfo:{
        ghtype1:{
            label:"房卡20赠20",
            goodType:"ghtype1",
            price:40,
            addition:40
        },
        ghtype2:{
            label:"房卡40赠40",
            goodType:"ghtype2",
            price:80,
            addition:80
        },
        ghtype3:{
            label:"房卡80赠80",
            goodType:"ghtype3",
            price:160,
            addition:160
        }
    },
    appPayInfo:{
        apptype1:{
            label:"房卡10赠4",
            goodType:"apptype1",
            price:20,
            addition:14
        },
        apptype2:{
            label:"房卡20赠10",
            goodType:"apptype2",
            price:40,
            addition:30
        },
        apptype3:{
            label:"房卡60赠38",
            goodType:"apptype3",
            price:120,
            addition:98
        },
        apptype4:{
            label:"房卡80赠58",
            goodType:"apptype4",
            price:160,
            addition:138
        },
        apptype5:{
            label:"房卡120赠88",
            goodType:"apptype5",
            price:240,
            addition:208
        },
        apptype6:{
            label:"房卡160赠128",
            goodType:"apptype6",
            price:320,
            addition:288
        },
    }
}